version: "3"

services:
  serversample:
    image: alphawolfsforce/jaws-schema-api:latest
    environment:
      ENV_NAME: dev
    ports:
      - 27017:27017
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-halbanaservice

