version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    
  server:
    image: 'alphawolfsforce/jaws-schema-api:latest'
    environment:
      ENV_NAME: dev
    ports:
      - '3000:3000'
    depends_on:
      - mongo
volumes: 
  mongo: