version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
    restart: always

  # rabbit:
  #   image: rabbitmq:3-management
  #   container_name: rabbit
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   restart: always
    
  server:
    image: 'alphawolfsforce/jaws-schema-api:latest'
    container_name: server
    # build:
    #   context: ../../server
    #   dockerfile: Dockerfile
    environment:
        PORT: "3000"
        MONGO_SCHEMA_COLLECTION_NAME: "schema"
        MONGO_PROPERTY_COLLECTION_NAME: "property"
        # MONGO_URI: "mongodb://Alpha:Alpha123456@51.124.152.60:27017"
        MONGO_URI: "mongodb://mongo:27017"
        CLIENT_URL: "http://client-nginx:3001"
        RABBIT_URI: "http://amqp://rabbit"
        QUEUE_NAME: "schema-instances-queue"
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      # - rabbit
      # -  client-nginx
    restart: always
volumes: 
  mongo: